# Generated by Django 3.2.12 on 2024-04-04 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='категория')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='наименование')),
                ('image', models.ImageField(upload_to='images/%Y', verbose_name='изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'unique_together': {('title',)},
            },
        ),
        migrations.CreateModel(
            name='TypeOfTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_test', models.CharField(choices=[('thin', 'тонкое'), ('traditional', 'традиционное')], max_length=12, verbose_name='тип теста')),
                ('product_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tests', to='product.product')),
            ],
            options={
                'verbose_name': 'тип теста',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('26cm', '26см'), ('30cm', '30см'), ('40cm', '40см')], max_length=4, verbose_name='размер')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_size', to='product.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'размер и цена',
                'verbose_name_plural': 'размеры и цены',
            },
        ),
    ]
